name = "lean-kernel-soundness-tools"
defaultTargets = ["LeanKernelSoundnessTools", "lean-kernel-check"]

[[lean_exe]]
name = "lean-kernel-check"
root = "Main"
rpath = ["/Users/jasonrute/.elan/toolchains/leanprover--lean4---v4.33.0-rc2/lib/lean"]

[[require]]
name = "lean4lean"
path = "/Users/jasonrute/Development/leanstral/prove_lean_correct/lean4lean"

[[require]]
name = "lean4lean-model"
path = "/Users/jasonrute/Development/leanstral/prove_lean_correct/lean4lean-model"

[[lean_lib]]
name = "LeanKernelSoundnessTools"
